services:
  database:
   image: postgres:14.2-alpine
   environment:
    POSTGRES_PASSWORD: example
   ports:
     - '5432:5432'
  strapi:
    image: strapi/strapi
    volumes:
      - ./app:/srv/app
    ports:
      - '1337:1337'
  html:
   image: nginx:1.21.6-alpine
   ports:
    - '8080:80'
   volumes:
     - ./html-server:/usr/share/nginx/html